### ISSUE TITLE
LaTeX toolbar

### ISSUE THREAD

**Issue by hermanzdosilovic** [codeassign/editor#3]
SimpleMDE comes with built-in set of toolbar icons, but it is easy to add custom toolbar icons - check it out [here](https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons).

We should add few icons (not sure which one) for easier writing of LaTeX symbols. I think that we should definitely add buttons for inserting inline LaTeX block `$` and also display block `$$`.

**Comment by kristijanbartol** [comment]
_Also should be done:
- "download to pdf" button
- edit fullscreen button to make it completely fullscreen

Optionally:
* create Latex button and add it to Font Awesome library_

**Comment by kristijanbartol** [comment]
"Download to PDF" could be better added to frontend (on the assignment page for every user to be able to download it). It simplifies editor and keeps it lightweight.

Fullscreen button can also stay as is, as user would actually rarely want to have the ability to make literally fullscreen.

For now, Latex button icons can be these graph icons.

TODO: **add keyboard shortcut for Latex expression.**

**Comment by kristijanbartol** [comment]
> The list of actions that can be bound is the same as the list of built-in actions available for toolbar buttons.

Not possible to use SimpleMDE keyboard shortcuts for custom buttons.
